apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: "client_id"  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "kvname"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    cloudEnvFileName: ""   # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectAlias: "SQL_USER"     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectAlias: "SQL_PASSWORD"
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLSERVER
          objectAlias: "SQL_SERVER"
          objectType: secret
          objectVersion: ""
        - |
          objectName: BINGMAPSKEY
          objectAlias: "BING_MAPS_KEY"
          objectType: secret
          objectVersion: ""
    resourceGroup: "teamResources"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "89eb5de7-be0a-4488-8b3a-a78358b2d3bb"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "b6995c8f-8cfc-4e17-8898-892cb00eb98a"                 # the tenant ID of the KeyVault